### ISSUE TITLE
DaggerImageDownloaderComponent class not found!

### ISSUE THREAD

**Issue by anupdey99** [omaflak/Dagger2-Sample#1]
import me.aflak.dagger.component.DaggerImageDownloaderComponent;
not found.!

**Comment by omaraflak** [comment]
Are you sure you cloned the repository correctly ? I just updated gradle for the repo and other stuffs...
You may want to try again : 

`git clone https://github.com/OmarAflak/Dagger2-Sample.git`

Then Android Studio > File > New > import Project

**Comment by kanimozhi123** [comment]
Hi Omar,I have to same issue DaggerImageDownloaderComponent cannot resolve. Kindly tell me the solution ASAP.

**Comment by omaraflak** [comment]
Try to clean and rebuild the project.
Also you may want to take a look at this repo instead : https://github.com/OmarAflak/Dagger2-CYS
I included a link to my tutorial on Dagger2.
